const DIRECT_IPA: Record<string, string> = {
  a: "ə",
  about: "əˈbaʊt",
  address: "əˈdres",
  addressed: "əˈdrest",
  again: "əˈɡen",
  airflow: "ˈeəfləʊ",
  all: "ɔːl",
  along: "əˈlɒŋ",
  aloud: "əˈlaʊd",
  alternated: "ˈɔːltəneɪtɪd",
  an: "ən",
  analytics: "ˌænəˈlɪtɪks",
  and: "ənd",
  annual: "ˈænjuəl",
  answers: "ˈɑːnsəz",
  arjun: "ˈɑːdʒən",
  at: "ət",
  awful: "ˈɔːfəl",
  balanced: "ˈbælənst",
  bank: "bæŋk",
  banner: "ˈbænə",
  battery: "ˈbætri",
  bedroom: "ˈbedruːm",
  before: "bɪˈfɔː",
  best: "best",
  board: "bɔːd",
  breath: "breθ",
  bridged: "brɪdʒd",
  brief: "briːf",
  briefed: "briːft",
  broad: "brɔːd",
  built: "bɪlt",
  by: "baɪ",
  caleb: "ˈkeɪləb",
  call: "kɔːl",
  called: "kɔːld",
  camera: "ˈkæmərə",
  captain: "ˈkæptɪn",
  caption: "ˈkæpʃən",
  caught: "kɔːt",
  centered: "ˈsentəd",
  checked: "tʃekt",
  chief: "tʃiːf",
  clarity: "ˈklærəti",
  classic: "ˈklæsɪk",
  clean: "kliːn",
  clear: "klɪə",
  cleared: "klɪəd",
  closed: "kləʊzd",
  cluster: "ˈklʌstə",
  cold: "kəʊld",
  consistency: "kənˈsɪstənsi",
  consonant: "ˈkɒnsənənt",
  control: "kənˈtrəʊl",
  cool: "kuːl",
  curious: "ˈkjʊəriəs",
  d: "diː",
  dark: "dɑːk",
  dashboard: "ˈdæʃbɔːd",
  data: "ˈdeɪtə",
  david: "ˈdeɪvɪd",
  delivered: "dɪˈlɪvəd",
  dental: "ˈdentəl",
  desk: "desk",
  detailed: "ˈdiːteɪld",
  direct: "dɪˈrekt",
  door: "dɔː",
  dr: "diː ɑː",
  draft: "drɑːft",
  drawer: "drɔː",
  dress: "dres",
  dressed: "drest",
  drift: "drɪft",
  drill: "drɪl",
  driver: "ˈdraɪvə",
  during: "ˈdjʊərɪŋ",
  e: "iː",
  edited: "ˈedɪtɪd",
  end: "end",
  evening: "ˈiːvnɪŋ",
  everest: "ˈevərɪst",
  every: "ˈevri",
  explained: "ɪkˈspleɪnd",
  export: "ˈekspɔːt",
  f: "ef",
  failed: "feɪld",
  fair: "feə",
  false: "fɔːls",
  family: "ˈfæməli",
  fast: "fɑːst",
  fault: "fɔːlt",
  faulty: "ˈfɔːlti",
  favourite: "ˈfeɪvərɪt",
  feature: "ˈfiːtʃə",
  feedback: "ˈfiːdbæk",
  felt: "felt",
  fer: "fɜː",
  few: "fjuː",
  file: "faɪl",
  files: "faɪlz",
  filter: "ˈfɪltə",
  final: "ˈfaɪnəl",
  fine: "faɪn",
  finish: "ˈfɪnɪʃ",
  finished: "ˈfɪnɪʃt",
  firewall: "ˈfaɪəwɔːl",
  firm: "fɜːm",
  firmware: "ˈfɜːmweə",
  first: "fɜːst",
  five: "faɪv",
  flawed: "flɔːd",
  flow: "fləʊ",
  fluency: "ˈfluːənsi",
  folder: "ˈfəʊldə",
  followed: "ˈfɒləʊd",
  footage: "ˈfʊtɪdʒ",
  for: "fə",
  forecast: "ˈfɔːkɑːst",
  form: "fɔːm",
  frame: "freɪm",
  free: "friː",
  fresh: "freʃ",
  freshly: "ˈfreʃli",
  fricative: "ˈfrɪkətɪv",
  friday: "ˈfraɪdeɪ",
  from: "frəm",
  frozen: "ˈfrəʊzən",
  full: "fʊl",
  funding: "ˈfʌndɪŋ",
  funnel: "ˈfʌnəl",
  gathering: "ˈɡæðərɪŋ",
  get: "get",
  global: "ˈɡləʊbəl",
  grade: "ɡreɪd",
  great: "ɡreɪt",
  guided: "ˈɡaɪdɪd",
  habitat: "ˈhæbɪtæt",
  had: "həd",
  half: "hɑːf",
  happen: "ˈhæpən",
  have: "hæv",
  headroom: "ˈhedruːm",
  hill: "hɪl",
  hotel: "həʊˈtel",
  i: "aɪ",
  ideas: "aɪˈdɪəz",
  import: "ˈɪmpɔːt",
  improved: "ɪmˈpruːvd",
  in: "ɪn",
  into: "ˈɪntuː",
  it: "ɪt",
  junior: "ˈdʒuːniə",
  kept: "kept",
  l: "el",
  landing: "ˈlændɪŋ",
  laptops: "ˈlæptɒps",
  law: "lɔː",
  leafy: "ˈliːfi",
  leandro: "liˈændrəʊ",
  leave: "liːv",
  lena: "ˈliːnə",
  letter: "ˈletə",
  life: "laɪf",
  light: "laɪt",
  linking: "ˈlɪŋkɪŋ",
  lip: "lɪp",
  live: "laɪv",
  ll: "l",
  loaded: "ˈləʊdɪd",
  lock: "lɒk",
  log: "lɒɡ",
  lot: "lɒt",
  lucy: "ˈluːsi",
  manager: "ˈmænɪdʒə",
  manual: "ˈmænjuəl",
  map: "mæp",
  marcus: "ˈmɑːkəs",
  medial: "ˈmiːdiəl",
  met: "met",
  mira: "ˈmɪərə",
  morning: "ˈmɔːnɪŋ",
  mouth: "maʊθ",
  move: "muːv",
  moved: "muːvd",
  natural: "ˈnætʃrəl",
  never: "ˈnevə",
  new: "njuː",
  non: "nɒn",
  nora: "ˈnɔːrə",
  not: "nɒt",
  note: "nəʊt",
  notes: "nəʊts",
  noun: "naʊn",
  o: "əʊ",
  of: "əv",
  off: "ɒf",
  old: "əʊld",
  on: "ɒn",
  one: "wʌn",
  open: "ˈəʊpən",
  order: "ˈɔːdə",
  our: "aʊə",
  output: "ˈaʊtpʊt",
  package: "ˈpækɪdʒ",
  packet: "ˈpækɪt",
  panel: "ˈpænəl",
  passage: "ˈpæsɪdʒ",
  pattern: "ˈpætən",
  pause: "pɔːz",
  pausing: "ˈpɔːzɪŋ",
  pedestrian: "pəˈdestriən",
  permit: "ˈpɜːmɪt",
  planet: "ˈplænɪt",
  planned: "plænd",
  plans: "plænz",
  please: "pliːz",
  policy: "ˈpɒləsi",
  position: "pəˈzɪʃən",
  pot: "pɒt",
  practice: "ˈpræktɪs",
  pro: "prəʊ",
  proactive: "prəʊˈæktɪv",
  problem: "ˈprɒbləm",
  process: "ˈprɒses",
  product: "ˈprɒdʌkt",
  program: "ˈprəʊɡræm",
  progress: "ˈprəʊɡres",
  project: "ˈprɒdʒekt",
  prompt: "prɒmpt",
  proof: "pruːf",
  proper: "ˈprɒpə",
  protest: "ˈprəʊtest",
  put: "pʊt",
  quiet: "ˈkwaɪət",
  quit: "kwɪt",
  r: "ɑː",
  radio: "ˈreɪdiəʊ",
  rail: "reɪl",
  random: "ˈrændəm",
  range: "reɪndʒ",
  ranking: "ˈræŋkɪŋ",
  rapid: "ˈræpɪd",
  rare: "reə",
  rate: "reɪt",
  ravi: "ˈrɑːvi",
  raw: "rɔː",
  reactions: "riˈækʃənz",
  read: "riːd",
  reader: "ˈriːdə",
  readers: "ˈriːdəz",
  reading: "ˈriːdɪŋ",
  ready: "ˈredi",
  real: "rɪəl",
  reason: "ˈriːzən",
  reasons: "ˈriːzənz",
  reception: "rɪˈsepʃən",
  record: "rɪˈkɔːd",
  recorded: "rɪˈkɔːdɪd",
  recording: "rɪˈkɔːdɪŋ",
  records: "ˈrekɔːdz",
  red: "red",
  redraft: "riːˈdrɑːft",
  redress: "rɪˈdres",
  register: "ˈredʒɪstə",
  regular: "ˈreɡjʊlə",
  rehearsal: "rɪˈhɜːsəl",
  rehearsals: "rɪˈhɜːsəlz",
  relaxed: "rɪˈlækst",
  release: "rɪˈliːs",
  relevant: "ˈreləvənt",
  reliable: "rɪˈlaɪəbəl",
  remarks: "rɪˈmɑːks",
  reminded: "rɪˈmaɪndɪd",
  remote: "rɪˈməʊt",
  repeated: "rɪˈpiːtɪd",
  repeating: "rɪˈpiːtɪŋ",
  repetition: "ˌrepəˈtɪʃən",
  replay: "ˈriːpleɪ",
  reply: "rɪˈplaɪ",
  report: "rɪˈpɔːt",
  reports: "rɪˈpɔːts",
  request: "rɪˈkwest",
  requested: "rɪˈkwestɪd",
  requests: "rɪˈkwests",
  research: "rɪˈsɜːtʃ",
  reset: "riːˈset",
  response: "rɪˈspɒns",
  responses: "rɪˈspɒnsɪz",
  result: "rɪˈzʌlt",
  results: "rɪˈzʌlts",
  review: "rɪˈvjuː",
  reviewed: "rɪˈvjuːd",
  reviewer: "rɪˈvjuːə",
  revisions: "rɪˈvɪʒənz",
  reward: "rɪˈwɔːd",
  rhythm: "ˈrɪðəm",
  ribbon: "ˈrɪbən",
  right: "raɪt",
  rigid: "ˈrɪdʒɪd",
  risky: "ˈrɪski",
  river: "ˈrɪvə",
  riya: "ˈriːjə",
  road: "rəʊd",
  roadmap: "ˈrəʊdmæp",
  robust: "rəˈbʌst",
  role: "rəʊl",
  roof: "ruːf",
  room: "ruːm",
  rough: "rʌf",
  round: "raʊnd",
  route: "ruːt",
  routes: "ruːts",
  routines: "ruːˈtiːnz",
  rubrics: "ˈruːbrɪks",
  rules: "ruːlz",
  runner: "ˈrʌnə",
  rural: "ˈrʊərəl",
  safe: "seɪf",
  said: "sed",
  save: "seɪv",
  saved: "seɪvd",
  saw: "sɔː",
  schedule: "ˈʃedjuːl",
  scheduled: "ˈʃedjuːld",
  school: "skuːl",
  sent: "sent",
  shadowing: "ˈʃædəʊɪŋ",
  shared: "ʃeəd",
  she: "ʃiː",
  shift: "ʃɪft",
  short: "ʃɔːt",
  slow: "sləʊ",
  small: "smɔːl",
  smooth: "smuːð",
  soft: "sɒft",
  solid: "ˈsɒlɪd",
  solving: "ˈsɒlvɪŋ",
  sonia: "ˈsəʊniə",
  speaking: "ˈspiːkɪŋ",
  speed: "spiːd",
  stable: "ˈsteɪbəl",
  status: "ˈsteɪtəs",
  steel: "stiːl",
  stiff: "stɪf",
  stilled: "stɪld",
  storm: "stɔːm",
  stress: "stres",
  strict: "strɪkt",
  strong: "strɒŋ",
  switched: "swɪtʃt",
  t: "tiː",
  take: "teɪk",
  talk: "tɔːk",
  talking: "ˈtɔːkɪŋ",
  tall: "tɔːl",
  tapped: "tæpt",
  target: "ˈtɑːɡɪt",
  teal: "tiːl",
  that: "ðæt",
  the: "ðə",
  then: "ðen",
  they: "ðeɪ",
  this: "ðɪs",
  thought: "θɔːt",
  threaded: "ˈθredɪd",
  tight: "taɪt",
  to: "tə",
  tonight: "təˈnaɪt",
  tracking: "ˈtrækɪŋ",
  traffic: "ˈtræfɪk",
  trained: "treɪnd",
  trans: "træns",
  transfer: "ˈtrænsfɜː",
  transition: "trænˈzɪʃən",
  transitions: "trænˈzɪʃənz",
  trap: "træp",
  twenty: "ˈtwenti",
  up: "ʌp",
  update: "ˈʌpdeɪt",
  updates: "ˈʌpdeɪts",
  upgrade: "ˈʌpɡreɪd",
  using: "ˈjuːzɪŋ",
  v: "viː",
  value: "ˈvæljuː",
  valve: "vælv",
  vays: "veɪz",
  vehicle: "ˈviːɪkəl",
  vera: "ˈvɪərə",
  verb: "vɜːb",
  version: "ˈvɜːʃən",
  very: "ˈveri",
  view: "vjuː",
  viewer: "ˈvjuːə",
  village: "ˈvɪlɪdʒ",
  visitors: "ˈvɪzɪtəz",
  vivid: "ˈvɪvɪd",
  vocal: "ˈvəʊkəl",
  voice: "vɔɪs",
  voices: "ˈvɔɪsɪz",
  vowel: "ˈvaʊəl",
  w: "ˈdʌbəljuː",
  walk: "wɔːk",
  walkway: "ˈwɔːkweɪ",
  wall: "wɔːl",
  warm: "wɔːm",
  warning: "ˈwɔːnɪŋ",
  warped: "wɔːpt",
  was: "wəz",
  waste: "weɪst",
  water: "ˈwɔːtə",
  ways: "weɪz",
  we: "wiː",
  weak: "wiːk",
  weather: "ˈweðə",
  weekend: "ˌwiːkˈend",
  weeks: "wiːks",
  well: "wel",
  west: "west",
  what: "wɒt",
  while: "waɪl",
  whistle: "ˈwɪsəl",
  white: "waɪt",
  whole: "həʊl",
  whose: "huːz",
  wide: "waɪd",
  width: "wɪdθ",
  window: "ˈwɪndəʊ",
  wire: "ˈwaɪə",
  with: "wɪð",
  without: "wɪˈðaʊt",
  witness: "ˈwɪtnəs",
  wolf: "wʊlf",
  won: "wʌn",
  wool: "wʊl",
  words: "wɜːdz",
  work: "wɜːk",
  worked: "wɜːkt",
  workflow: "ˈwɜːkfləʊ",
  worry: "ˈwʌri",
  wrong: "rɒŋ",
  wrote: "rəʊt",
  year: "jɪə",
  yearly: "ˈjɪəli",
  yod: "jɒd",
  your: "jɔː",
  active: "ˈæktɪv",
  age: "eɪdʒ",
  approximant: "əˈprɒksɪmənt",
  archive: "ˈɑːkaɪv",
  around: "əˈraʊnd",
  audience: "ˈɔːdiəns",
  autumn: "ˈɔːtəm",
  availability: "əˌveɪləˈbɪləti",
  bandage: "ˈbændɪdʒ",
  be: "biː",
  black: "blæk",
  bottle: "ˈbɒtəl",
  br: "biː ɑː",
  branch: "brɑːntʃ",
  brand: "brænd",
  branded: "ˈbrændɪd",
  brave: "breɪv",
  brazil: "brəˈzɪl",
  bread: "bred",
  breezy: "ˈbriːzi",
  brewery: "ˈbruːəri",
  bridge: "brɪdʒ",
  bright: "braɪt",
  brisk: "brɪsk",
  broadcast: "ˈbrɔːdkɑːst",
  broken: "ˈbrəʊkən",
  brown: "braʊn",
  butter: "ˈbʌtə",
  calm: "kɑːm",
  careful: "ˈkeəfəl",
  carriage: "ˈkærɪdʒ",
  carry: "ˈkæri",
  cautious: "ˈkɔːʃəs",
  center: "ˈsentə",
  check: "tʃek",
  citation: "saɪˈteɪʃən",
  city: "ˈsɪti",
  civil: "ˈsɪvəl",
  clock: "klɒk",
  close: "kləʊz",
  code: "kəʊd",
  coffee: "ˈkɒfi",
  comment: "ˈkɒment",
  common: "ˈkɒmən",
  completely: "kəmˈpliːtli",
  concise: "kənˈsaɪs",
  connected: "kəˈnektɪd",
  copy: "ˈkɒpi",
  correct: "kəˈrekt",
  corridor: "ˈkɒrɪdɔː",
  cottage: "ˈkɒtɪdʒ",
  courage: "ˈkʌrɪdʒ",
  cover: "ˈkʌvə",
  coverage: "ˈkʌvərɪdʒ",
  cream: "kriːm",
  creative: "kriˈeɪtɪv",
  crowd: "kraʊd",
  cycle: "ˈsaɪkəl",
  damage: "ˈdæmɪdʒ",
  day: "deɪ",
  diphthong: "ˈdɪfθɒŋ",
  doctor: "ˈdɒktə",
  "doctor's": "ˈdɒktəz",
  dosage: "ˈdəʊsɪdʒ",
  down: "daʊn",
  drainage: "ˈdreɪnɪdʒ",
  driven: "ˈdrɪvən",
  forward: "ˈfɔːwəd",
  frontage: "ˈfrʌntɪdʒ",
  function: "ˈfʌŋkʃən",
  go: "ɡəʊ",
  gone: "ɡɒn",
  here: "hɪə",
  home: "həʊm",
  honest: "ˈɒnɪst",
  hot: "hɒt",
  image: "ˈɪmɪdʒ",
  known: "nəʊn",
  labiodental: "ˌleɪbiəʊˈdentəl",
  lane: "leɪn",
  late: "leɪt",
  lawful: "ˈlɔːfəl",
  leakage: "ˈliːkɪdʒ",
  lineage: "ˈlɪniɪdʒ",
  load: "ləʊd",
  locker: "ˈlɒkə",
  longer: "ˈlɒŋɡə",
  loud: "laʊd",
  low: "ləʊ",
  luggage: "ˈlʌɡɪdʒ",
  marriage: "ˈmærɪdʒ",
  me: "miː",
  message: "ˈmesɪdʒ",
  mileage: "ˈmaɪlɪdʒ",
  model: "ˈmɒdəl",
  modern: "ˈmɒdn",
  monitor: "ˈmɒnɪtə",
  mortgage: "ˈmɔːɡɪdʒ",
  movement: "ˈmuːvmənt",
  my: "maɪ",
  night: "naɪt",
  now: "naʊ",
  offer: "ˈɒfə",
  office: "ˈɒfɪs",
  online: "ˌɒnˈlaɪn",
  onset: "ˈɒnset",
  option: "ˈɒpʃən",
  orphanage: "ˈɔːfənɪdʒ",
  outcome: "ˈaʊtkʌm",
  over: "ˈəʊvə",
  overvalued: "ˌəʊvəˈvæljuːd",
  percentage: "pəˈsentɪdʒ",
  phone: "fəʊn",
  postage: "ˈpəʊstɪdʒ",
  profile: "ˈprəʊfaɪl",
  promise: "ˈprɒmɪs",
  quality: "ˈkwɒləti",
  quick: "kwɪk",
  reaction: "riˈækʃən",
  refresh: "rɪˈfreʃ",
  remark: "rɪˈmɑːk",
  s: "es",
  same: "seɪm",
  search: "sɜːtʃ",
  selective: "sɪˈlektɪv",
  sentence: "ˈsentəns",
  sequence: "ˈsiːkwəns",
  server: "ˈsɜːvə",
  service: "ˈsɜːvɪs",
  setting: "ˈsetɪŋ",
  sewage: "ˈsuːɪdʒ",
  shop: "ʃɒp",
  shortage: "ˈʃɔːtɪdʒ",
  shorter: "ˈʃɔːtə",
  shortly: "ˈʃɔːtli",
  shoulder: "ˈʃəʊldə",
  signage: "ˈsaɪnɪdʒ",
  signal: "ˈsɪɡnəl",
  silence: "ˈsaɪləns",
  silent: "ˈsaɪlənt",
  simple: "ˈsɪmpəl",
  single: "ˈsɪŋɡəl",
  slope: "sləʊp",
  slowly: "ˈsləʊli",
  social: "ˈsəʊʃəl",
  sound: "saʊnd",
  speech: "spiːtʃ",
  station: "ˈsteɪʃən",
  steady: "ˈstedi",
  story: "ˈstɔːri",
  stronger: "ˈstrɒŋɡə",
  subtle: "ˈsʌtəl",
  sudden: "ˈsʌdən",
  sunny: "ˈsʌni",
  sweet: "swiːt",
  syrup: "ˈsɪrəp",
  system: "ˈsɪstəm",
  tage: "tɪdʒ",
  tone: "təʊn",
  tonnage: "ˈtʌnɪdʒ",
  topic: "ˈtɒpɪk",
  trailer: "ˈtreɪlə",
  trusted: "ˈtrʌstɪd",
  type: "taɪp",
  uploaded: "ʌpˈləʊdɪd",
  useful: "ˈjuːsfəl",
  valid: "ˈvælɪd",
  variety: "vəˈraɪəti",
  verify: "ˈverɪfaɪ",
  video: "ˈvɪdiəʊ",
  vintage: "ˈvɪntɪdʒ",
  virtual: "ˈvɜːtʃuəl",
  visible: "ˈvɪzəbəl",
  vision: "ˈvɪʒən",
  visual: "ˈvɪʒuəl",
  vital: "ˈvaɪtəl",
  voiceless: "ˈvɔɪsləs",
  voltage: "ˈvəʊltɪdʒ",
  volume: "ˈvɒljuːm",
  voucher: "ˈvaʊtʃə",
  wait: "weɪt",
  wanted: "ˈwɒntɪd",
  watch: "wɒtʃ",
  wave: "weɪv",
  waveform: "ˈweɪffɔːm",
  welcoming: "ˈwelkəmɪŋ",
  word: "wɜːd",
  workspace: "ˈwɜːkspeɪs",
  worldwide: "ˌwɜːldˈwaɪd",
  zone: "zəʊn"
};

const VOICELESS_ENDINGS = ["p", "t", "k", "f", "s", "ʃ", "tʃ", "θ"];
const SIBILANT_ENDINGS = ["s", "z", "ʃ", "ʒ", "tʃ", "dʒ"];

function normalizeWord(raw: string) {
  return raw.toLowerCase().replace(/’/g, "'");
}

function endsWithPhoneme(ipa: string, endings: string[]) {
  return endings.some((ending) => ipa.endsWith(ending));
}

function withEd(baseIpa: string) {
  if (baseIpa.endsWith("t") || baseIpa.endsWith("d")) return `${baseIpa}ɪd`;
  if (endsWithPhoneme(baseIpa, VOICELESS_ENDINGS)) return `${baseIpa}t`;
  return `${baseIpa}d`;
}

function withS(baseIpa: string) {
  if (endsWithPhoneme(baseIpa, SIBILANT_ENDINGS)) return `${baseIpa}ɪz`;
  if (endsWithPhoneme(baseIpa, VOICELESS_ENDINGS)) return `${baseIpa}s`;
  return `${baseIpa}z`;
}

function withIng(baseWord: string, baseIpa: string) {
  if (baseWord.endsWith("e") && !baseWord.endsWith("ee")) {
    return `${baseIpa.replace(/eɪ$/, "eɪ")}ɪŋ`;
  }
  if (baseWord.endsWith("y")) {
    return `${baseIpa}ɪŋ`;
  }
  return `${baseIpa}ɪŋ`;
}

function transcribeWord(rawWord: string): string {
  const word = normalizeWord(rawWord);
  if (DIRECT_IPA[word]) return DIRECT_IPA[word];

  if (word.endsWith("'ll")) {
    const stem = word.slice(0, -3);
    const stemIpa = transcribeWord(stem);
    return `${stemIpa}l`;
  }

  if (word.endsWith("ed")) {
    const stem1 = word.slice(0, -2);
    const stem2 = word.slice(0, -1);
    const base = DIRECT_IPA[stem1] ? stem1 : DIRECT_IPA[stem2] ? stem2 : null;
    if (base) return withEd(DIRECT_IPA[base]);
  }

  if (word.endsWith("ing")) {
    const stem = word.slice(0, -3);
    const stemE = `${stem}e`;
    if (DIRECT_IPA[stem]) return withIng(stem, DIRECT_IPA[stem]);
    if (DIRECT_IPA[stemE]) return withIng(stemE, DIRECT_IPA[stemE]);
  }

  if (word.endsWith("s")) {
    const stem = word.slice(0, -1);
    if (DIRECT_IPA[stem]) return withS(DIRECT_IPA[stem]);
  }

  throw new Error(`No IPA mapping for word: ${word}`);
}

export function toModernRpSentenceIpa(sentence: string) {
  const words = sentence.match(/[A-Za-z]+(?:'[A-Za-z]+)?/g) ?? [];
  const phonemes = words.map((word) => transcribeWord(word));
  return `/${phonemes.join(" ")}/`;
}
